import BaseAudioGraphNodeModule from './BaseAudioGraphNodeModule';

class InstrumentModule extends BaseAudioGraphNodeModule {

    constructor(target: any, audioContext: any, params: any) {
            
        let proxy: any = null;

        super(target, audioContext, params, {

            //Instrument
            trigger: async (options?: any | null) => {

                const opt = options || {}

                //Generate frequencies
                // if(proxy.signalSource){
                //     const {count} = params.signalSource.options;
                //     this.frequencyArray = proxy.signalSource.generate(count[0], count[1], 'linear');
                //     opt.frequency = this.frequencyArray
                //     console.log('[' + opt.frequency.join(', ') + ']')
                // }
                
                //init all
                await this.init(opt);
                await this.connect();
        
                let autoReleaseDelayMs;
                
                if(params.autoRelease){
                    if(typeof params.duration === 'undefined'){
                        throw new Error(params.name + ' missing duration prop, required for autoRelease')
                    }
                    autoReleaseDelayMs = params.duration * 1000
                } 

                this.start(this.context.currentTime, opt, autoReleaseDelayMs);
        
            }, 

            //Instrument
            stop: async (options?: any | null) => {

                const opt = options || {}

                //use frequencies generated by the last attack
                opt.frequency = this.frequencyArray

                // stop sources
                for(let src of this.sources){
                    src.stop(opt);
                }

        
            }

        });

        // if(params.signalSource) {
        //     if(params.signalSource.function.toLowerCase() === 'primes'){
        //         const {range} = params.signalSource.options;
        //         this.signalSource = new Primes(range[0], range[1]);
        //     }
        // }



        this.$type = 'Instrument';

        proxy = this;
        
    }
}

export default InstrumentModule;